[VBLOCKS-1417] Outgoing call screen and active call screen
twilio/twilio-voice-react-native-app pull request #5
Opened 2023-02-02 17:37 UTC by mhuynh5757

This pull request includes the outgoing call screen and active call screen part 1 (without active call banner).

https://issues.corp.twilio.com/browse/VBLOCKS-1417

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

2023-02-07 16:08 UTC, charliesantos requested changes
Initial review on the app/ level files.

2023-02-07 17:17 UTC, mhuynh5757 commented on app/__tests__/store.test.ts
> +});
Yeah, I wanted to test at least the happy path for the application state. I think we're going to want to use something like Storybook down the line.

2023-02-07 18:01 UTC, charliesantos commented
I reviewed the app code and kudos to you @mhuynh5757 . This is a lot of work! However, there's an issue I noticed and maybe you can help me understand. We are using redux, but I cannot see/understand the pattern that you're trying to do. The way it's currently setup, the data flow looks like this
```
Screens/Components <------> State/Store
```

On a redux pattern, I'm expecting actions, reducers, and components that interacts with the state/store in the following manner
```
Components ----> Dispatch Actions ----> Store Reducers ----> State ---> Components
```
And have folder structure that maps to this data flow - `components`, `actions`, `reducers`. I noticed you have `screens` folder, which is fine btw.

My request is, please explain what pattern you're trying to use. If it's not industry standard or something you came up with, please explain why. We need to understand pros and cons.

2023-02-07 19:30 UTC, charliesantos commented
Notes and action items base on our discussion:
- Move the hooks into separate files/folders
- Actions and Reducers are good. Need to document the pattern and file structure we're using
- Rename `Other` component to something more meaningful
- Document the distinction between screens and components
We should submit a ticket to address the action items. But we need to rename `Other` component now :)

2023-02-08 19:22 UTC, mhuynh5757 commented on app/README.md
> +* TODO
Looked at the PRD again, didn't see `Contact List` so I'll leave it out of the README for now. Let me know if we should add it anyways.

2023-02-08 23:54 UTC, mhuynh5757 commented on app/README.md
> +# Reference App
I won't resolve this one yet since we have work slated for branding down the line, leaving it for posterity.

2023-02-09 00:20 UTC, charliesantos approved these changes

2023-02-09 00:43 UTC, merged