[VBLOCKS-1834] Refactor auth util
twilio/twilio-voice-react-native-app pull request #79
Opened 2023-06-30 18:55 UTC by mhuynh5757

## Submission Checklist

 - [ ] The `CHANGELOG.md` reflects any **feature**, **bug fixes**, or **known issues** made in the source code
 - [ ] New unit tests and integration tests have beed added
 - [x] Code coverage is more or equal to the previous coverage
 - [x] A visual inspection of the `Files changed` tab was made prior to submitting the pull request ensuring the style guide was followed
 - [ ] [CI pipeline](https://app.circleci.com/pipelines/github/twilio/twilio-voice-react-native-app) is green
 - [x] ~Included screenshot if necessary~

## Description

Move user actions into the store and have clean separation of concerns for auth libraries in the auth util. With these changes, a fork of this project can reasonably replace solely the auth util with their own implementation and not have to change the store.

## Breakdown

- Move auth0 related functions to auth util
- Use auth util in the user store actions
- Adjust imports and unit tests

## Validation

- Unit tests
- Manual testing

## Additional Notes

N/A

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

2023-06-30 19:34 UTC, charliesantos requested changes

2023-06-30 19:34 UTC, charliesantos commented on app/src/store/user.ts
> +  reason: 'AUTH_UTIL_REJECTED';
Why not `AUTH_REJECTED`?

2023-06-30 19:56 UTC, mhuynh5757 commented on app/src/store/user.ts
> +  reason: 'AUTH_UTIL_REJECTED';
Works for me, I can change it.

2023-06-30 20:02 UTC, charliesantos approved these changes

2023-06-30 21:24 UTC, kpchoy approved these changes
🚢

2023-07-03 17:58 UTC, charliesantos approved these changes

2023-07-03 18:01 UTC, kpchoy approved these changes

2023-07-03 18:02 UTC, merged